image: node:12

stages:
  - deploy

deploy-component:
  stage: deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - cat .npmrc
    - npm publish

  tags:
    - general
    - time4vps

  only:
    - main
