const DEFAULT_DATE_FORMAT = 'yyyy-MM-dd'
const DEFAULT_TIME_FORMAT = 'HH:mm:ss'
const DEFAULT_DIALOG_WIDTH = 360
const DEFAULT_CLEAR_TEXT = 'CLEAR'
const DEFAULT_OK_TEXT = 'OK'
const DEFAULT_START_TEXT = 'Start'
const DEFAULT_END_TEXT = 'End'

export {
  DEFAULT_DATE_FORMAT,
  DEFAULT_TIME_FORMAT,
  DEFAULT_DIALOG_WIDTH,
  DEFAULT_CLEAR_TEXT,
  DEFAULT_OK_TEXT,
  DEFAULT_START_TEXT,
  DEFAULT_END_TEXT
}